### ISSUE TITLE
You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by masyanru** [replicaJunction/PSJira#27]
Jira v6.4.10#64025
Powershell Version is 5.0.10586.122

I've installed the PSJira module and Set-JiraConfigServer, after that you can see details below ...

PS C:\> New-JiraSession -Credential (Get-Credential)

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
WARNING: JIRA returned HTTP error  -
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PSJira\1.2.4.85\Functions\New-JiraSession.ps1:92 char:13
+             $readStream = New-Object -TypeName System.IO.StreamReader ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by replicaJunction** [comment]
I actually just ran into this issue myself. It's probably a problem with the server URL in your config file - if you copy/paste from Chrome, it adds a trailing slash to the URL, which messes up the script module.

Check your config.xml file to see if your URL ends with a trailing slash, and remove it if it's there. Otherwise, it's a different issue completely.

I've also added some smarts to Set-JiraConfigServer to strip trailing slashes in the future.
