### ISSUE TITLE
Feature Request/Question: Return JSON switch for Get-JIRAIssueCreateMetaData

### ISSUE THREAD

**Issue by sipho102** [replicaJunction/PSJira#3]
Hey there

Really appreciate this PS Module. Saving me hours of work coding this myself.
This might be more of a question than a feature request:
Is there a reason you return self created custom PSObjects for Get-JIRAIssueCreateMetaData with less data than returned by the REST method?
Noticed this when I was looking for the allowed values, which are lost as they are not handed over.
For now I built in a switch $returnJSON to the cmdlet which returns the $fields object instead of the custom object. This did the trick for me but wanted to know why it was designed like that. And maybe as an improvement for the future.

Cheers

**Comment by replicaJunction** [comment]
Thanks for pointing this out. To be honest, it's because this was one of the first functions I wrote, and I haven't touched it again since!

I do prefer outputting as an object because that's closer to the PowerShell way (provides a lot more flexibility in sorting & filtering, too), but there's no real reason to return less data than JIRA sends back.  I've added that in commit 027317a; could you take a look and see if the latest build meets your needs better?

**Comment by sipho102** [comment]
Wow. Way better than i expected :) 
Latest build works for me thanks :+1:
