### ISSUE TITLE
Encoding return problem with Invoke-JiraMethod

### ISSUE THREAD

**Issue by npadgham** [replicaJunction/PSJira#7]
Great project! I can see myself getting tons of use from this module. 

I found what I believed to be a problem with the encoding of data returned from Get-JiraIssue (and presumably other Get operations that rely on /PSJira/Functions/Internal/Invoke-JiraMethod.ps1).

When returning information from issues containing non-standard characters (such as "é"), the get-jiraissue would return "??" indicating an encoding issue.

I had a crack at finding and fixing the problem. Testing with the Invoke-JiraMethod function I could see characters present and correct in objects returned from the Invoke-WebRequest cmdlet. When processing the object through ConvertFrom-Json the characters are lost. ConvertFrom-Json seems to break encoding of the input object. However, if I pass along just the Content property of the returned web request object, the processing by ConvertFrom-Json returns a result with correct characters.

I have forked the code for Invoke-JiraMethod with the proposed change. I'm not 100% sure if this change would have some negative impact, but it's worked well with the tests I have performed with the get-jiraissue function.

By the way, I'm new to Git Hub - so please don't hesitate to correct me/advise me if I'm going about this all wrong!

Neil

**Comment by replicaJunction** [comment]
Hi Neil, and thanks for your pull request!

The Pester tests for Invoke-JiraMethod failed with your change to Invoke-Jira ([details on AppVeyor](https://ci.appveyor.com/project/JoshuaT/psjira/build/1.2.2.58)) but your change makes sense.  After a bit of testing, it looks like Invoke-WebRequest mocks were no longer adequate - now it matters that they return an object with the Content property, not just a String.

It looks like all tests pass with that change.  I've rolled your pull request into a new branch (66d5290), and I'll get that merged to master here in a bit.

Your change also reminded me that I don't have an active dev branch, so I'll create that branch and document that I prefer pull requests to go there instead of to master. :)

Thanks again!
replica

**Comment by replicaJunction** [comment]
I've got your change and the associated test changes uploaded to the dev branch.
